---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/about/_index.md
  label: about
- type: document
  path: content/contact/_index.md
  label: contact
- type: directory
  path: content/portfolio
  label: portfolio
  create: documents
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.50'
